name: Feature request
description: Suggest a new capability or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline the change
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks / tradeoffs
    validations:
      required: false
